/* Corpus Explorer — renders the structured public corpus generated by
   scripts/build_corpus.py. Everything on this page is read from the generated
   corpus.js artifact at load time; no numbers are typed into the HTML. */
(function () {
  "use strict";

  var corpus = (typeof window !== "undefined") ? window.PBS_CORPUS : null;

  if (typeof window === "undefined" || !document.getElementById("cx-chunks")) {
    return;
  }

  var chunksEl = document.getElementById("cx-chunks");
  var pageSelect = document.getElementById("cx-page-filter");
  var textInput = document.getElementById("cx-text-filter");
  var countEl = document.getElementById("cx-count");
  var checksEl = document.getElementById("cx-checks");

  function el(tag, className, text) {
    var node = document.createElement(tag);
    if (className) node.className = className;
    if (text !== undefined) node.textContent = text;
    return node;
  }

  function setStat(id, value) {
    var node = document.getElementById(id);
    if (node) node.textContent = value;
  }

  if (!corpus || !corpus.chunks || !corpus.meta) {
    chunksEl.appendChild(el("p", "cx-error",
      "The corpus artifact failed to load. Run scripts/build_corpus.py to regenerate corpus.js."));
    return;
  }

  var chunks = corpus.chunks;
  var meta = corpus.meta;

  /* ── Stats (all read from the artifact) ── */
  setStat("cx-stat-chunks", String(meta.chunk_count));
  setStat("cx-stat-pages", String(meta.pages.length));
  setStat("cx-stat-chars", meta.total_chars.toLocaleString());
  setStat("cx-stat-avg", chunks.length ? Math.round(meta.total_chars / chunks.length) + " chars" : "—");
  setStat("cx-stat-generated", meta.generated);

  /* ── Boundary checks, computed live against the artifact ── */
  var approved = {};
  meta.pages.forEach(function (p) { approved[p.page] = true; });

  var seen = {};
  var duplicateIds = chunks.filter(function (c) {
    if (seen[c.id]) return true;
    seen[c.id] = true;
    return false;
  }).length;
  var outsideBoundary = chunks.filter(function (c) { return !approved[c.page]; }).length;
  var missingFields = chunks.filter(function (c) {
    return !c.id || !c.anchor || !c.content_sha1 || !c.text;
  }).length;
  var privateLeaks = chunks.filter(function (c) {
    return c.page.indexOf("private/") === 0;
  }).length;

  [
    { label: "Chunk ids unique", detail: duplicateIds + " duplicates", pass: duplicateIds === 0 },
    { label: "Every chunk from an approved public page", detail: outsideBoundary + " outside the allowlist", pass: outsideBoundary === 0 },
    { label: "No private/ paths in the corpus", detail: privateLeaks + " found", pass: privateLeaks === 0 },
    { label: "Every chunk has id, anchor, text, and content hash", detail: missingFields + " incomplete", pass: missingFields === 0 }
  ].forEach(function (check) {
    var li = el("li", check.pass ? "is-pass" : "is-fail");
    li.appendChild(el("span", "cx-check-state", check.pass ? "Pass" : "Fail"));
    li.appendChild(el("span", "cx-check-label", check.label));
    li.appendChild(el("span", "cx-check-detail", check.detail));
    checksEl.appendChild(li);
  });

  /* ── Page filter options ── */
  meta.pages.forEach(function (p) {
    var option = document.createElement("option");
    option.value = p.page;
    option.textContent = p.title + " (" + chunks.filter(function (c) { return c.page === p.page; }).length + ")";
    pageSelect.appendChild(option);
  });

  /* ── Chunk cards ── */
  function preview(text) {
    return text.length > 240 ? text.slice(0, 240).replace(/\s+\S*$/, "") + " …" : text;
  }

  function render() {
    var page = pageSelect.value;
    var needle = textInput.value.trim().toLowerCase();
    chunksEl.textContent = "";

    var shown = chunks.filter(function (c) {
      if (page && c.page !== page) return false;
      if (!needle) return true;
      return (c.id + " " + c.title + " " + c.text).toLowerCase().indexOf(needle) !== -1;
    });

    countEl.textContent = shown.length + " of " + chunks.length + " chunks";

    if (!shown.length) {
      chunksEl.appendChild(el("p", "cx-empty",
        "No chunks match. That is an honest empty state — the corpus only contains approved public content."));
      return;
    }

    shown.forEach(function (c) {
      var card = el("article", "cx-chunk");

      var head = el("div", "cx-chunk-head");
      head.appendChild(el("h3", "", c.title));
      head.appendChild(el("span", "cx-chunk-page", c.page_title));
      card.appendChild(head);

      card.appendChild(el("p", "cx-chunk-text", preview(c.text)));

      var metaRow = el("div", "cx-chunk-meta");
      metaRow.appendChild(el("code", "cx-chunk-id", c.id));
      metaRow.appendChild(el("span", "", c.chars + " chars"));
      metaRow.appendChild(el("span", "", "sha1 " + c.content_sha1));
      card.appendChild(metaRow);

      var link = el("a", "cx-chunk-link", "Open source section →");
      link.href = "../../" + c.page + "#" + c.anchor;
      link.setAttribute("aria-label", "Open source section: " + c.title);
      card.appendChild(link);

      chunksEl.appendChild(card);
    });
  }

  pageSelect.addEventListener("change", render);
  textInput.addEventListener("input", render);
  render();
})();
